config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #
  # Defines the root path route ("/")
  # root "articles#index"

  draw :holidays
  draw :infomations
  draw :admin
  draw :users
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root 'top#index'
  end
  get 'health_check', to: 'health_check#index', as: 'health_check'

  # :nocov:
  mount LetterOpenerWeb::Engine => '/letter_opener' if Rails.env.development?
  # :nocov:
end

app/views/layouts/_development.html.erb
<h5>development</h5>
<ul>
  <li><%= link_to 'LetterOpenerWeb', letter_opener_web_path %></li>
  <li><%= link_to 'ActionMailer Preview', '/rails/mailers' %></li>
<% if admin %>
  <li><%= link_to t('app_name'), root_path %></li>
<% else %>
  <li><%= link_to "#{t('app_name')} Admin", new_admin_user_session_path %></li>
<% end %>
</ul>

app/views/layouts/admin_users.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title><%= content_for?(:html_title) ? yield(:html_title) + ' - ' : '' %><%= "#{t('app_name')} Admin#{t("env_name.#{Settings.server_env}")}" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
    <link rel="stylesheet" href="<%= config.asset_host %>/css/mdb.min.css?v3.1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
<% if Settings.locales.keys.count >= 2 %>
    <%= javascript_import_module_tag 'controllers/switch_locale' %>
<% end %>
  </head>
  <body>
    <header style="margin-bottom: 52px">
      <nav class="navbar navbar-light bg-warning fixed-top p-0">
        <div class="container-fluid">
          <a href="<%= new_admin_user_session_path %>" class="navbar-brand">
            <%= t('app_name') %> Admin
            <span class="d-none d-sm-block"><%= t("env_name.#{Settings.server_env}") %></span>
          </a>
          <nav class="nav align-items-center">
<% unless admin_user_signed_in? %>
            <a href="<%= new_admin_user_session_path %>" class="nav-link d-flex align-items-center link-dark">
              <i class="fas fa-sign-in-alt fa-lg"></i>
              <span class="d-none d-md-block m-1"><%= t('ログイン') %></span>
            </a>
<% else %>
            <div class="text-truncate d-none d-lg-block" style="max-width: 400px">
              <%= "current_admin_user.name" %>
            </div>
            <a href="<%= destroy_admin_user_session_path %>" class="nav-link d-flex align-items-center link-dark">
              <i class="fas fa-sign-out-alt fa-lg"></i>
              <span class="d-none d-md-block m-1"><%= t('ログアウト') %></span>
            </a>
<% end %>
<% if Settings.locales.keys.count >= 2 %>
            <div class="p-2">
              <%= select_tag 'switch_locale', options_for_select(Settings.locales.map { |code, name| [name, code] }, I18n.locale) %>
            </div>
<% end %>
          </nav>
        </div>
      </nav>
    </header>

    <main class="container-lg">
<% if alert.present? %>
      <aside>
        <p class="note note-danger mb-2"><%= alert %></p>
      </aside>
<% end %>
<% if notice.present? %>
      <aside>
        <p class="note note-success mb-2"><%= notice %></p>
      </aside>
<% end %>
      <%= yield %>
    </main>

    <footer class="bg-light">
      <div class="text-center p-3">
        Copyright &copy; <%= link_to t('my_name'), t('my_url'), target: :_blank, rel: %i[noopener noreferrer] %> All Rights Reserved.
      </div>
      <%= render '/layouts/development', admin: true if Rails.env.development? %>
    </footer>
  </body>
  <script type="text/javascript" src="<%= config.asset_host %>/js/mdb.min.js?v3.1.0"></script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title><%= content_for?(:html_title) ? yield(:html_title) + ' - ' : '' %><%= "#{t('app_name')}#{t("env_name.#{Settings.server_env}")}" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
    <link rel="stylesheet" href="<%= config.asset_host %>/css/mdb.min.css?v3.1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
<% if Settings.debug %>
    <meta name="debug" content="true">
<% end %>
    <%= javascript_importmap_tags %>
    <%= javascript_import_module_tag 'controllers/left_menu' %>
<% if Settings.locales.keys.count >= 2 %>
    <%= javascript_import_module_tag 'controllers/switch_locale' %>
<% end %>
  </head>
  <body>
    <header style="margin-bottom: 70px">
      <nav class="navbar navbar-light bg-light fixed-top" style="padding-top: 8px">
        <div id="nav_area" class="container-fluid px-1">
          <div class="d-flex">
            <div id="nav_left">
              <button id='left_menu_display_btn' type="button" class="btn btn-link btn-rounded p-3">
                <i class="fa fa-bars text-body" style="font-size: 20px"></i>
              </button>
            </div>
            <a href="<%= root_path %>" class="navbar-brand">
              <%= image_tag "/logo.png", id: 'app_logo', width: '40px', height: '40px' %>
              <span id="app_name" class="text-truncate" style="max-width: 125px"><%= "#{t('app_name')}#{t('sub_title')}#{t("env_name.#{Settings.server_env}")}" %></span>
            </a>
          </div>
          <nav id="nav_right" class="nav align-items-center">
<% unless user_signed_in? %>
            <a href="<%= new_user_session_path %>" class="btn btn-link btn-rounded d-flex align-items-center link-dark p-2" style="font-size: 1rem">
              <i class="fas fa-sign-in-alt fa-lg"></i>
              <span class="d-none d-md-block m-1"><%= t('ログイン') %></span>
            </a>
            <a href="<%= new_user_registration_path %>" class="btn btn-link btn-rounded d-flex align-items-center link-dark p-2" style="font-size: 1rem">
              <i class="fas fa-user-plus fa-lg"></i>
              <span class="d-none d-md-block m-1"><%= t('アカウント登録') %></span>
            </a>
<% else %>
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a id="userDropdownToggle" href="#" class="dropdown-toggle btn-link d-flex align-items-center link-dark p-2" style="max-width: 400px" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                  <%= image_tag current_user.image_url(:small), class: 'rounded-circle' %>
                  <span class="text-truncate d-none d-lg-block ms-1"><%= current_user.name %></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdownToggle">
                  <li>
                    <a href="<%= edit_user_registration_path %>" class="dropdown-item">
                      <i class="fas fa-user-edit"></i>
                      <span class="m-2"><%= t('ユーザー情報') %></span>
                    </a>
                  </li>
                  <li>
                    <a href="<%= delete_user_session_path %>" class="dropdown-item">
                      <i class="fas fa-sign-out-alt"></i>
                      <span class="m-2"><%= t('ログアウト') %></span>
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
            <a href="<%= infomations_path %>" class="btn btn-link btn-rounded link-dark" style="font-size: 1rem">
              <i class="fas fa-bell fa-lg">
<% if current_user.infomation_unread_count > 0 %>
                <span class="badge rounded-pill badge-notification bg-danger" style="top: -10px; left: -5px"><%= current_user.infomation_unread_count %></span>
<% end %>
              </i>
            </a>
<% end %>
<% if Settings.locales.keys.count >= 2 %>
            <div class="p-2">
              <%= select_tag 'switch_locale', options_for_select(Settings.locales.map { |code, name| [name, code] }, I18n.locale) %>
            </div>
<% end %>
          </nav>
        </div>
      </nav>
    </header>

    <div class="d-flex">
      <nav id="left_menu" class="nav flex-column bg-light" style="width: 300px; min-width: 300px; display: none">
<% unless user_signed_in? %>
        <a href="<%= new_user_session_path %>" class="btn btn-link d-flex align-items-center link-dark" style="font-size: 1rem">
          <i class="fas fa-sign-in-alt fa-lg"></i>
          <span class="mx-2 my-1"><%= t('ログイン') %></span>
        </a>
        <a href="<%= new_user_registration_path %>" class="btn btn-link d-flex align-items-center link-dark" style="font-size: 1rem">
          <i class="fas fa-user-plus fa-lg"></i>
          <span class="mx-2 my-1"><%= t('アカウント登録') %></span>
        </a>
<% else %>
        <div id="userAccordionFlush" class="accordion accordion-flush">
          <div class="accordion-item">
            <div id="userAccordionHeader" class="accordion-header">
              <button
                class="accordion-button px-3 py-2<%= ' collapsed' unless show_user_accordion? %>"
                data-mdb-toggle="collapse"
                data-mdb-target="#userAccordionCollapse"
                aria-expanded="true"
                aria-controls="userAccordionCollapse"
              >
                <%= image_tag current_user.image_url(:small), class: 'rounded-circle' %>
                <span class="text-truncate text-start ms-1" style="width: 200px"><%= current_user.name %></span>
              </button>
            </div>
            <div
              id="userAccordionCollapse"
              class="accordion-collapse collapse<%= ' show' if show_user_accordion? %>"
              aria-labelledby="userAccordionHeader"
              data-mdb-parent="#userAccordionFlush"
            >
              <div class="accordion-body py-1">
                <a href="<%= edit_user_registration_path %>" class="btn btn-link d-flex align-items-center link-dark px-3" style="font-size: 1rem">
                  <i class="fas fa-user-edit"></i>
                  <span class="mx-2 my-1"><%= t('ユーザー情報') %></span>
                </a>
                <a href="<%= delete_user_session_path %>" class="btn btn-link d-flex align-items-center link-dark px-3" style="font-size: 1rem">
                  <i class="fas fa-sign-out-alt"></i>
                  <span class="mx-2 my-1"><%= t('ログアウト') %></span>
                </a>
              </div>
            </div>
          </div>
        </div>
<% end %>
        <hr class="my-0" />
        <a href="<%= infomations_path %>" class="btn btn-link d-flex align-items-center link-dark" style="font-size: 1rem">
          <i class="fas fa-bell fa-lg">
<% if user_signed_in? && current_user.infomation_unread_count > 0 %>
            <span class="badge rounded-pill badge-notification bg-danger" style="top: -10px; left: -5px"><%= current_user.infomation_unread_count %></span>
<% end %>
          </i>
          <span class="mx-2 my-1"><%= t('お知らせ') %></span>
        </a>
      </nav>

      <main id="main_contents" class="flex-grow-1" style="min-width: 300px">
        <div class="mx-3 mt-3 mb-1">
<% if user_destroy_reserved_message? %>
          <aside>
            <p class="note note-warning mb-2">
              <%= t('アカウント削除情報', date: l(current_user.destroy_schedule_at.to_date)) %>
              <%= link_to t('取り消しはこちら'), delete_undo_user_registration_path %>
            </p>
          </aside>
<% end %>
<% if alert.present? %>
          <aside>
            <p class="note note-danger mb-2"><%= alert %></p>
          </aside>
<% end %>
<% if notice.present? %>
          <aside>
            <p class="note note-success mb-2"><%= notice %></p>
          </aside>
<% end %>
          <%= yield %>
        </div>
      </main>
    </div>

    <footer id="footer" class="bg-light" style="min-width: 300px">
      <div class="d-flex justify-content-center p-3">
        <span class="d-none d-sm-block">Copyright&nbsp;</span><span class="text-truncate">&copy; <%= link_to t('my_name'), t('my_url'), target: :_blank, rel: %i[noopener noreferrer] %> All Rights Reserved.</span>
      </div>
      <%= render '/layouts/development', admin: false if Rails.env.development? %>
    </footer>
  </body>
  <script type="text/javascript" src="<%= config.asset_host %>/js/mdb.min.js?v3.1.0"></script>
</html>

app/views/layouts/none.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title><%= content_for?(:html_title) ? yield(:html_title) + ' - ' : '' %><%= "#{t('app_name')}#{t("env_name.#{Settings.server_env}")}" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>